// ESP32 sensor pack firmware - scaffold (GitHub issue #4) + device claim
// (GitHub issue #23) + telemetry send / command receive / actuator control
// (GitHub issue #24).
//
// Scope: Wi-Fi connect, DHT22 read, LED/fan GPIO control (issue #4),
// AP-mode Wi-Fi provisioning + device claim (issue #23, see src/claim and
// src/wifi_provisioning), and the recurring telemetry POST + piggybacked
// command receive/execute/ACK cycle (issue #24, see src/telemetry and
// src/actuators). See README.md for what is and isn't covered by
// automated tests (hardware-dependent pieces are not host-testable).
//
// Pin numbers, Wi-Fi credentials, and the API endpoint are never
// hardcoded here; static bench-testing values come from include/config.h
// (git-ignored, generated by copying include/config.example.h). Real
// deployments instead claim their Wi-Fi credentials + device token at
// runtime via the AP-mode flow and persist them to NVS (see
// wifi_provisioning::has_stored_device_token/load_stored_credentials).

#include <Arduino.h>
#include <DHT.h>
#include <WiFi.h>

#include <string>
#include <vector>

#include "actuators/actuator_driver.h"
#include "actuators/actuator_state.h"
#include "config.h"
#include "telemetry/ack_queue.h"
#include "telemetry/telemetry_client.h"
#include "telemetry/telemetry_protocol.h"
#include "telemetry_format.h"
#include "wifi_provisioning/ap_provisioning.h"

static DHT dht(DHT_PIN, DHT_SENSOR_TYPE);
static uint32_t g_nextSeq = 0;
// Populated once at boot from NVS after a successful claim (see setup()).
// Not reassigned afterwards; loop() only reads it.
static std::string g_device_token;

// Builds a single-command batch and routes it through the same
// resolve_commands()/actuators::apply_desired_state() path the real
// telemetry-response command dispatch (loop(), issue #24) uses, so the
// boot self-test below exercises the actual wiring rather than a
// duplicate/parallel code path.
static CommandDelivery makeSelfTestCommand(const char* command_type) {
    CommandDelivery command;
    command.idempotency_key = "boot-self-test";
    command.command_type = command_type;
    command.issued_at = "";
    return command;
}

static void connectToWiFi(const std::string& ssid, const std::string& password) {
    if (ssid.empty()) {
        // Fail closed: no fallback network, no silently-skipped connection.
        // This should not happen in practice - has_stored_device_token()
        // gates entry here, and a successful claim always persists a
        // non-empty SSID alongside the token - but we check explicitly
        // rather than trusting that invariant silently.
        Serial.println(
            "[FATAL] Resolved Wi-Fi SSID is empty even though a device "
            "token is stored in NVS. Halting rather than connecting to an "
            "unintended network. This indicates corrupted/partial NVS "
            "state; re-provisioning (erase NVS) is required.");
        while (true) {
            delay(1000);
        }
    }

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid.c_str(), password.c_str());
    Serial.print("[INFO] Connecting to Wi-Fi");

    const unsigned long startedAt = millis();
    while (WiFi.status() != WL_CONNECTED) {
        if (millis() - startedAt > WIFI_CONNECT_TIMEOUT_MS) {
            Serial.println();
            Serial.println(
                "[ERROR] Wi-Fi connection timed out. Will retry on next "
                "boot cycle; not proceeding with a disconnected radio.");
            return;
        }
        delay(500);
        Serial.print(".");
    }

    Serial.println();
    Serial.print("[INFO] Wi-Fi connected. IP: ");
    Serial.println(WiFi.localIP());
}

// One-shot actuator wiring self-test at boot. This only proves the pin
// config + resolve_commands()/actuator_driver wiring is correct; it is not
// the real command dispatch loop (that runs in loop() below, driven by
// commands piggybacked on the telemetry response - issue #24).
static void runActuatorSelfTestOnce() {
    const std::vector<CommandDelivery> ledOnBatch{makeSelfTestCommand("LED_ON")};
    actuators::apply_desired_state(resolve_commands(ledOnBatch).desired_state);

    delay(200);

    const std::vector<CommandDelivery> ledOffBatch{makeSelfTestCommand("LED_OFF")};
    actuators::apply_desired_state(resolve_commands(ledOffBatch).desired_state);
}

void setup() {
    Serial.begin(115200);

    pinMode(LED_PIN, OUTPUT);
    pinMode(FAN_RELAY_PIN, OUTPUT);
    // Fail-safe boot state: both actuators OFF until an explicit command
    // says otherwise. No actuator is ever energized by default.
    digitalWrite(LED_PIN, LOW);
    digitalWrite(FAN_RELAY_PIN, LOW);

    dht.begin();

    if (!wifi_provisioning::has_stored_device_token()) {
        // First boot (or a claim never completed): block here in AP-mode
        // provisioning (issue #23, requirements.md F1.3-F1.5). This only
        // returns on success, then restarts the device so the branch below
        // runs on the next boot with real stored credentials.
        Serial.println(
            "[INFO] No claimed device token in NVS. Starting AP-mode "
            "provisioning.");
        wifi_provisioning::run_provisioning_flow();
    }

    const wifi_provisioning::StoredCredentials creds =
        wifi_provisioning::load_stored_credentials();
    g_device_token = creds.device_token;
    connectToWiFi(creds.wifi_ssid, creds.wifi_password);

    runActuatorSelfTestOnce();

    Serial.println(
        "[INFO] Firmware ready (claimed). Telemetry send / command "
        "receive / ACK (issue #24) runs every TELEMETRY_INTERVAL_MS in "
        "loop().");
}

void loop() {
    static unsigned long lastReadAt = 0;
    // Idempotency keys of commands executed locally but not yet confirmed
    // -ACKed to the server (requirements.md F5.3). Function-scope static
    // (like lastReadAt above) rather than a file-scope global, per
    // coding-style.md - state stays confined to the one function that owns
    // the telemetry cycle.
    static std::vector<std::string> pendingCommandAcks;

    const unsigned long now = millis();
    if (now - lastReadAt < TELEMETRY_INTERVAL_MS) {
        return;
    }
    lastReadAt = now;

    const float humidity = dht.readHumidity();
    const float temperature = dht.readTemperature();

    if (isnan(humidity) || isnan(temperature)) {
        // DHT22 read failures happen (timing-sensitive 1-wire protocol).
        // We log and skip this cycle rather than transmitting/fabricating
        // a substitute value.
        Serial.println(
            "[ERROR] DHT22 read failed (NaN). Skipping this cycle.");
        return;
    }

    if (!is_valid_reading(temperature, humidity)) {
        Serial.println(
            "[ERROR] DHT22 reading outside the documented valid range "
            "(requirements.md F2.4). Discarding sample.");
        return;
    }

    const TelemetryRequestData requestData{g_nextSeq++, temperature, humidity,
                                            pendingCommandAcks};

    const telemetry::TelemetryCycleResult cycleResult =
        telemetry::send_telemetry(g_device_token, requestData);

    if (!cycleResult.transport_ok) {
        // Offline, or every retry attempt failed at the transport layer
        // (telemetry_client.cpp already logged the specific reason). The
        // ack queue is left untouched so the same pending ACKs are retried
        // on the next TELEMETRY_INTERVAL_MS tick - this is the required
        // "basic offline/retry behavior" (issue #24 acceptance criteria).
        return;
    }

    if (!cycleResult.response.parsed_ok) {
        // Definitive HTTP error (400/401/410) or an unparseable 200 body
        // (telemetry_protocol.cpp already recorded the reason). Never
        // execute commands from, or drain the ack queue based on, a
        // response we could not fully trust.
        Serial.println(
            "[ERROR] Telemetry request was rejected or returned an "
            "unparseable response. Skipping command processing this "
            "cycle.");
        return;
    }

    // The server has now confirmed receipt of this request, including
    // whichever ACKs were snapshotted into requestData - drain exactly
    // those from the pending queue (requirements.md F5.3: dedup is
    // server-side, but we still avoid re-sending confirmed ACKs forever).
    remove_acked(pendingCommandAcks, requestData.pending_command_acks);

    if (!cycleResult.response.accepted) {
        Serial.println(
            "[WARN] Server reported accepted=false for this reading "
            "(value-range rejection or duplicate seq - requirements.md "
            "F2.4/F2.5).");
    }

    const ApplyCommandsResult applyResult =
        resolve_commands(cycleResult.response.commands);
    actuators::apply_desired_state(applyResult.desired_state);

    for (const std::string& idempotencyKey : applyResult.applied_idempotency_keys) {
        enqueue_pending_ack(pendingCommandAcks, idempotencyKey);
    }

    for (const std::string& idempotencyKey :
         applyResult.unrecognized_idempotency_keys) {
        // No fallback execution for a commandType this firmware does not
        // recognize (coding-style.md "フォールバック処理を書かない") - left
        // un-ACKed so it expires server-side via TTL (requirements.md
        // F5.4) rather than being silently dropped or guessed at.
        Serial.print(
            "[ERROR] Received command with unrecognized commandType "
            "(idempotencyKey=");
        Serial.print(idempotencyKey.c_str());
        Serial.println("). Not executed, not ACKed.");
    }
}
