// ESP32 sensor pack firmware - scaffold (GitHub issue #4) + device claim
// (GitHub issue #23).
//
// Scope: Wi-Fi connect, DHT22 read, a minimal LED/fan control stub (issue
// #4), and AP-mode Wi-Fi provisioning + device claim (issue #23, see
// src/claim and src/wifi_provisioning). Telemetry/command networking + ACK
// (issue #24) is NOT implemented here - see README.md for what is and
// isn't covered by this scaffold.
//
// Pin numbers, Wi-Fi credentials, and the API endpoint are never
// hardcoded here; static bench-testing values come from include/config.h
// (git-ignored, generated by copying include/config.example.h). Real
// deployments instead claim their Wi-Fi credentials + device token at
// runtime via the AP-mode flow and persist them to NVS (see
// wifi_provisioning::has_stored_device_token/load_stored_credentials).

#include <Arduino.h>
#include <DHT.h>
#include <WiFi.h>

#include <string>

#include "command_mapper.h"
#include "config.h"
#include "telemetry_format.h"
#include "wifi_provisioning/ap_provisioning.h"

static DHT dht(DHT_PIN, DHT_SENSOR_TYPE);
static uint32_t g_nextSeq = 0;
// Populated once at boot from NVS after a successful claim (see setup()).
// Not reassigned afterwards; loop() only reads it.
static std::string g_device_token;

static void setActuator(Actuator actuator, bool energized) {
    const int pin = (actuator == Actuator::LED) ? LED_PIN : FAN_RELAY_PIN;
    digitalWrite(pin, energized ? HIGH : LOW);
}

static void connectToWiFi(const std::string& ssid, const std::string& password) {
    if (ssid.empty()) {
        // Fail closed: no fallback network, no silently-skipped connection.
        // This should not happen in practice - has_stored_device_token()
        // gates entry here, and a successful claim always persists a
        // non-empty SSID alongside the token - but we check explicitly
        // rather than trusting that invariant silently.
        Serial.println(
            "[FATAL] Resolved Wi-Fi SSID is empty even though a device "
            "token is stored in NVS. Halting rather than connecting to an "
            "unintended network. This indicates corrupted/partial NVS "
            "state; re-provisioning (erase NVS) is required.");
        while (true) {
            delay(1000);
        }
    }

    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid.c_str(), password.c_str());
    Serial.print("[INFO] Connecting to Wi-Fi");

    const unsigned long startedAt = millis();
    while (WiFi.status() != WL_CONNECTED) {
        if (millis() - startedAt > WIFI_CONNECT_TIMEOUT_MS) {
            Serial.println();
            Serial.println(
                "[ERROR] Wi-Fi connection timed out. Will retry on next "
                "boot cycle; not proceeding with a disconnected radio.");
            return;
        }
        delay(500);
        Serial.print(".");
    }

    Serial.println();
    Serial.print("[INFO] Wi-Fi connected. IP: ");
    Serial.println(WiFi.localIP());
}

// One-shot actuator wiring self-test at boot. This only proves the pin
// config + command_mapper wiring is correct; it is not the real command
// dispatch loop (that arrives with HTTP command polling in issue #24).
static void runActuatorSelfTestOnce() {
    const CommandEffect ledOn = parse_command("LED_ON");
    if (ledOn.recognized) {
        setActuator(ledOn.actuator, ledOn.desired_state);
    }
    delay(200);
    const CommandEffect ledOff = parse_command("LED_OFF");
    if (ledOff.recognized) {
        setActuator(ledOff.actuator, ledOff.desired_state);
    }
}

void setup() {
    Serial.begin(115200);

    pinMode(LED_PIN, OUTPUT);
    pinMode(FAN_RELAY_PIN, OUTPUT);
    // Fail-safe boot state: both actuators OFF until an explicit command
    // says otherwise. No actuator is ever energized by default.
    digitalWrite(LED_PIN, LOW);
    digitalWrite(FAN_RELAY_PIN, LOW);

    dht.begin();

    if (!wifi_provisioning::has_stored_device_token()) {
        // First boot (or a claim never completed): block here in AP-mode
        // provisioning (issue #23, requirements.md F1.3-F1.5). This only
        // returns on success, then restarts the device so the branch below
        // runs on the next boot with real stored credentials.
        Serial.println(
            "[INFO] No claimed device token in NVS. Starting AP-mode "
            "provisioning.");
        wifi_provisioning::run_provisioning_flow();
    }

    const wifi_provisioning::StoredCredentials creds =
        wifi_provisioning::load_stored_credentials();
    g_device_token = creds.device_token;
    connectToWiFi(creds.wifi_ssid, creds.wifi_password);

    runActuatorSelfTestOnce();

    Serial.println(
        "[INFO] Firmware ready (claimed). Telemetry/command networking "
        "(#24) is implemented in a later issue - readings are logged, not "
        "yet transmitted.");
}

void loop() {
    static unsigned long lastReadAt = 0;
    const unsigned long now = millis();

    if (now - lastReadAt < TELEMETRY_INTERVAL_MS) {
        return;
    }
    lastReadAt = now;

    const float humidity = dht.readHumidity();
    const float temperature = dht.readTemperature();

    if (isnan(humidity) || isnan(temperature)) {
        // DHT22 read failures happen (timing-sensitive 1-wire protocol).
        // We log and skip this cycle rather than transmitting/fabricating
        // a substitute value.
        Serial.println(
            "[ERROR] DHT22 read failed (NaN). Skipping this cycle.");
        return;
    }

    if (!is_valid_reading(temperature, humidity)) {
        Serial.println(
            "[ERROR] DHT22 reading outside the documented valid range "
            "(requirements.md F2.4). Discarding sample.");
        return;
    }

    const TelemetryReading reading{g_device_token, g_nextSeq++, temperature,
                                    humidity};
    const std::string payload = format_telemetry_payload(reading);

    // Networking (HTTP POST to the backend, issue #24) is intentionally not
    // implemented yet; we only log what would be sent.
    Serial.print(
        "[DEBUG] Telemetry payload (not transmitted - HTTP wiring is "
        "issue #24): ");
    Serial.println(payload.c_str());
}
