/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のログインユーザー情報を取得する */
        get: operations["getSession"];
        put?: never;
        /**
         * Googleログインセッションを開始する
         * @description Next.js側でGoogle OAuth 2.0 / OpenID Connectを完了した後のIDトークンをRailsへ渡し、
         *     検証成立時にhttpOnlyセッションCookieを発行する。ログイン導線にはreCAPTCHAを適用する
         *     （requirements.md 1.3節・8節）。Google `sub` 値はDB照合にのみ使用し、レスポンスには含めない。
         */
        post: operations["createSession"];
        /** ログアウトする（セッションcookieを失効させる） */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分が所有する拠点一覧を取得する（テナント分離必須・F6.1） */
        get: operations["listSites"];
        put?: never;
        /** 拠点を新規作成する */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 拠点を論理削除する（配下デバイスも論理削除対象） */
        delete: operations["deleteSite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/claim-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * クレームコードを発行する（F1 claim_device 手順1-2）
         * @description ユーザーがダッシュボードの「デバイス追加」からreCAPTCHAを通過して要求する。
         *     8桁英数字コードを生成し、有効期限15分・対象拠点・発行ユーザー(sub)と共に保存する。
         */
        post: operations["issueClaimCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ESP32がクレームコードを提出しデバイストークンを取得する（F1 claim_device 手順3-6）
         * @description ESP32がAPモード経由で取得したクレームコードを送信する。未使用・期限内・失敗回数5回未満の
         *     コードと照合し、成立したらデバイスレコード(provisioning状態)を作成して長寿命のデバイストークンを返す。
         *     照合失敗が同一コードで累計5回に達すると、そのコードは即時失効する（総当たり対策）。
         *     IP単位のレート制限も併用する。
         */
        post: operations["claimDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の拠点配下の全デバイス一覧を取得する */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** デバイス詳細を取得する（F6.3 デバイス詳細画面） */
        get: operations["getDevice"];
        put?: never;
        post?: never;
        /** デバイスを論理削除する（再登録は新しいクレームコードで新デバイス扱い） */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/telemetry-series": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /**
         * デバイスの時系列グラフ用データを取得する（F6.3）
         * @description 直近24hは生データ、7日を超える範囲は日次1時間粒度の集約データを返す
         *     （生データは14日で削除・requirements.md 1.6 F6.5）。
         */
        get: operations["getDeviceTelemetrySeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ESP32からのテレメトリを受信し、閾値判定を同期実行し、未配信コマンドをピギーバック返却する
         * @description F2 ingest_telemetry / F3 evaluate_thresholds / F5 dispatch_command(配信) を1リクエストで処理する。
         *
         *     - デバイストークンを検証し、無効・論理削除済みなら401/410で拒否する。
         *     - 記録時刻はサーバー受信時刻を採用する（`device_reported_at`は参考値として保持のみ）。
         *     - 値域チェック（温度-40〜85℃、湿度0〜100%）を逸脱した値は不正データとして破棄し、
         *       破棄件数をデバイス統計に記録する（レスポンス自体は200のまま、`accepted=false`で通知）。
         *     - `device_id + seq` の組で重複排除する（再送による二重計上防止）。
         *     - 保存後に`last_seen`を更新し、閾値判定（連続3回・ヒステリシス）を同期実行する。
         *     - レスポンスに、当該デバイス宛の未配信コマンド（TTL内・issued_at昇順・最大5件）をピギーバック同梱する。
         *     - リクエストに前回コマンドのACK（`command_acks`）が含まれる場合、該当コマンドを`done`にする。
         *       同一冪等IDの重複ACKは無視する。
         */
        post: operations["ingestTelemetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** デバイスの閾値設定一覧を取得する */
        get: operations["getDeviceThresholds"];
        /**
         * デバイスの閾値（発報値・デッドバンド）を設定する（UC6）
         * @description 閾値が未設定のメトリクス・方向の組は判定をスキップする（requirements.md 1.6 F3.6）。
         *     既定デッドバンドは温度1.0℃・湿度3%。
         */
        put: operations["updateDeviceThresholds"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/commands": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** デバイスのコマンド履歴を取得する（F6.3） */
        get: operations["listCommands"];
        put?: never;
        /**
         * LED/ファンの手動制御コマンドを発行する（F5 dispatch_command 手順1）
         * @description 対象デバイスの所有者チェックを必ず行う。冪等ID付きでキューに積む（状態:pending, TTL10分）。
         *     オフライン中のデバイスへの発行も許可するが、UIで「オフラインのため復帰後TTL内のみ実行」と警告表示する
         *     （警告表示自体はNext.js側の責務。本APIは`device_status`をレスポンスに含めることで判断材料を提供する）。
         *     手動コマンド発行後30分間は、同一アクチュエータへの自動ルール発行を抑止する（オーバーライドウィンドウ）。
         */
        post: operations["createCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}/automation-rule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        /** 自動制御ルール設定を取得する（UC9） */
        get: operations["getAutomationRule"];
        /** 自動制御ルールを設定する（温度上限アラートでファンON/OFF・LEDは現地表示灯として自動制御） */
        put: operations["updateAutomationRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の拠点配下の全アラートを一覧取得する（UC7） */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alertId}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** アラートをacknowledgeする（closeは解除条件成立による自動のみ・手動close不可） */
        post: operations["acknowledgeAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/sites-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拠点一覧サマリーを取得する（F6.2・30秒ポーリング想定） */
        get: operations["getDashboardSitesSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-summaries/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当日中に生成済みのサマリーがあれば取得する（クォータ消費なし） */
        get: operations["getTodaySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI日次サマリーを生成する（F7 generate_daily_summary）
         * @description クォータ日＝JSTの現在時刻から3時間引いた日付。同一クォータ日に既に生成済みなら429で拒否し、
         *     既存の保存済みサマリーを併せて返す。過去24hテレメトリ統計とアラート履歴の**統計値のみ**
         *     （個人情報なし）をFastAPI(internal-ai)経由でLLMに渡す。データが存在しない場合はLLMを呼ばず
         *     「データ不足」の定型文を返し、クォータは消費しない。
         */
        post: operations["generateDailySummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全ユーザー横断のデバイス一覧を参照する（開発者用管理画面） */
        get: operations["adminListDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/ai-quota-reset": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 指定ユーザーのAIクォータを手動リセットする（F7.5） */
        post: operations["adminResetAiQuota"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ai/summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 統計値からAI日次サマリーの本文を生成する（Rails内部呼び出し専用）
         * @description Rails APIがgenerateDailySummary処理の一環として呼び出す内部エンドポイント。
         *     個人情報（ユーザーID・拠点名・デバイス識別子等）は一切含めず、統計値のみを送信する。
         *     LangChain経由でLLMへ渡し、日本語の自然言語サマリーを生成して返す。
         */
        post: operations["internalGenerateSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @description 機械可読なエラーコード（例：invalid_device_token, device_deleted, quota_exceeded, validation_error, forbidden, not_found） */
                code: string;
                /** @description 人間可読なエラーメッセージ（i18nキーはNext.js側で別途解決する場合はcodeを利用する） */
                message: string;
                details?: {
                    [key: string]: unknown;
                } | null;
            };
        };
        /** @description Googleログインの内部表現。opaqueな内部IDのみを保持し、sub値・メール・氏名は一切含めない（requirements.md 1.4節）。 */
        User: {
            /** @description 内部の不透明なユーザーID（Google subそのものではない） */
            id: string;
            /** Format: date-time */
            createdAt: string;
        };
        SessionCreateRequest: {
            /** @description Next.js側のGoogle OAuth 2.0 / OpenID Connectフローで取得したGoogle IDトークン(JWT) */
            idToken: string;
            /** @description ログイン導線に適用されるreCAPTCHAトークン */
            recaptchaToken: string;
        };
        SessionCreateResponse: {
            user: components["schemas"]["User"];
        };
        Site: {
            /** Format: int64 */
            id: number;
            /** @description 自由入力の拠点ラベル（住所ではない。例：「倉庫A」） */
            name: string;
            deviceCount: number;
            onlineDeviceCount: number;
            openAlertCount: number;
            latestTemperatureC?: number | null;
            latestHumidityPct?: number | null;
            /** Format: date-time */
            createdAt: string;
        };
        SiteCreateRequest: {
            /** @description プレースホルダは「倉庫A」等の例示に留め、住所入力を促すバリデーションは行わない */
            name: string;
        };
        /** @enum {string} */
        DeviceStatus: "provisioning" | "online" | "offline";
        Device: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            siteId: number;
            status: components["schemas"]["DeviceStatus"];
            /**
             * @description テレメトリ送信間隔（既定60秒）
             * @default 60
             */
            expectedIntervalSec: number;
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceDetail: components["schemas"]["Device"] & {
            thresholds: components["schemas"]["Threshold"][];
            automationRule?: components["schemas"]["AutomationRule"] | null;
        };
        ClaimCodeCreateRequest: {
            /** Format: int64 */
            siteId: number;
            recaptchaToken: string;
        };
        ClaimCodeCreateResponse: {
            /** @description 8桁英数字のクレームコード */
            code: string;
            /**
             * Format: date-time
             * @description 発行時刻+15分
             */
            expiresAt: string;
        };
        DeviceClaimRequest: {
            code: string;
        };
        DeviceClaimResponse: {
            /** Format: int64 */
            deviceId: number;
            /** @description 長寿命のデバイストークン（ESP32が以後の全リクエストで使用） */
            deviceToken: string;
        };
        /** @enum {string} */
        SensorTypeCode: "temperature" | "humidity";
        /** @enum {string} */
        ThresholdDirection: "upper" | "lower";
        /** @enum {string} */
        BreachState: "NORMAL" | "BREACHED";
        Threshold: {
            sensorType: components["schemas"]["SensorTypeCode"];
            direction: components["schemas"]["ThresholdDirection"];
            /** @description 発報閾値 */
            triggerValue: number;
            /** @description 解除までの不感帯（既定：温度1.0℃、湿度3%） */
            deadband: number;
            breachState: components["schemas"]["BreachState"];
        };
        ThresholdUpdateRequest: {
            thresholds: {
                sensorType: components["schemas"]["SensorTypeCode"];
                direction: components["schemas"]["ThresholdDirection"];
                triggerValue: number;
                deadband: number;
            }[];
        };
        TelemetryIngestRequest: {
            /** @description device_idとの組で重複排除する連番 */
            seq: number;
            temperatureC: number;
            humidityPct: number;
            /**
             * Format: date-time
             * @description 端末申告時刻（参考値。記録時刻はサーバー受信時刻を採用する）
             */
            deviceReportedAt?: string | null;
            /** @description 前回配信されたコマンドの実行結果ACK（冪等ID）。同一冪等IDの重複ACKは無視される。 */
            commandAcks?: {
                /** Format: uuid */
                idempotencyKey: string;
            }[];
        };
        CommandDelivery: {
            /** Format: uuid */
            idempotencyKey: string;
            commandType: components["schemas"]["CommandTypeCode"];
            /** Format: date-time */
            issuedAt: string;
        };
        TelemetryIngestResponse: {
            /** @description 値域チェックに合格し保存されたか（falseの場合は不正データとして破棄・統計にのみ記録） */
            accepted: boolean;
            /** @description device_id+seqの重複により保存をスキップした場合true */
            duplicate?: boolean;
            /** Format: date-time */
            serverTime: string;
            /** @description 未配信コマンド（TTL内・issued_at昇順・最大5件） */
            commands: components["schemas"]["CommandDelivery"][];
        };
        /** @enum {string} */
        CommandTypeCode: "LED_ON" | "LED_OFF" | "FAN_ON" | "FAN_OFF";
        /** @enum {string} */
        CommandOrigin: "manual" | "auto";
        /** @enum {string} */
        CommandStatus: "pending" | "delivered" | "done" | "expired";
        CommandCreateRequest: {
            commandType: components["schemas"]["CommandTypeCode"];
        };
        Command: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            deviceId: number;
            commandType: components["schemas"]["CommandTypeCode"];
            /** Format: uuid */
            idempotencyKey: string;
            origin: components["schemas"]["CommandOrigin"];
            status: components["schemas"]["CommandStatus"];
            /** Format: date-time */
            issuedAt: string;
            /**
             * Format: date-time
             * @description issuedAt + 10分
             */
            expiresAt: string;
        };
        AutomationRule: {
            /** @description 温度上限アラートopenでFAN_ON、closeでFAN_OFFを自動発行する */
            fanOnTempAlert: boolean;
            /** @description アラートopen中の現地表示灯としてLEDを自動制御する */
            ledOnAlert: boolean;
            /**
             * Format: date-time
             * @description 手動コマンド発行後30分間、同一アクチュエータへの自動ルール発行を抑止する期限
             */
            manualOverrideUntil?: string | null;
        };
        AutomationRuleUpdateRequest: {
            fanOnTempAlert?: boolean;
            ledOnAlert?: boolean;
        };
        /** @enum {string} */
        AlertTypeCode: "upper_breach" | "lower_breach" | "offline";
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "critical";
        /** @enum {string} */
        AlertStatus: "open" | "acknowledged" | "closed";
        Alert: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            deviceId: number;
            alertType: components["schemas"]["AlertTypeCode"];
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            acknowledgedAt?: string | null;
            /** Format: date-time */
            closedAt?: string | null;
        };
        TelemetrySeriesPoint: {
            /**
             * Format: date-time
             * @description 生データの場合はrecorded_at、集約データの場合はhour_bucket
             */
            timestamp: string;
            temperatureC?: number | null;
            humidityPct?: number | null;
            /** @description 7日を超えるデータは日次1時間粒度に集約済み（min/max/avgのavgのみ本フィールドで代表表示、詳細は将来拡張） */
            isAggregated: boolean;
        };
        AiSummary: {
            /**
             * Format: date
             * @description JSTの現在時刻から3時間引いた日付（JST03:00リセットと等価）
             */
            quotaDate: string;
            /** @description 日本語の自然言語サマリー。データ不足の場合は定型文。 */
            summaryText: string;
            /** Format: date-time */
            generatedAt: string;
            /** @description falseの場合「データ不足」の定型文であり、LLM呼び出し・クォータ消費は発生していない */
            dataSufficient: boolean;
        };
        AiSummaryQuotaExceeded: {
            error: {
                /** @enum {string} */
                code: "quota_exceeded";
                message: string;
            };
            existingSummary: components["schemas"]["AiSummary"];
        };
        InternalAiStats: {
            temperature: components["schemas"]["InternalAiMetricStats"];
            humidity: components["schemas"]["InternalAiMetricStats"];
        };
        InternalAiMetricStats: {
            min: number;
            max: number;
            avg: number;
            thresholdBreachMinutes: {
                upper?: number;
                lower?: number;
            };
        };
        InternalAiAlertSummary: {
            alertType: components["schemas"]["AlertTypeCode"];
            severity: components["schemas"]["AlertSeverity"];
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt?: string | null;
        };
        /** @description 個人情報（ユーザーID・拠点名・デバイス識別子）を一切含まない統計値のみのペイロード */
        InternalAiSummaryRequest: {
            stats: components["schemas"]["InternalAiStats"];
            alerts: components["schemas"]["InternalAiAlertSummary"][];
        };
        InternalAiSummaryResponse: {
            /** @description 日本語の自然言語サマリー本文 */
            summaryText: string;
        };
    };
    responses: {
        /** @description 未認証、またはセッション/トークンが無効 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証は成功しているが、他ユーザーのリソースへのアクセス（テナント分離違反） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リソースが存在しない、または論理削除済み */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リクエスト形式・値域の検証エラー */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        SiteId: number;
        DeviceId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログイン中 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description セッション確立成功 */
            200: {
                headers: {
                    /** @description httpOnly・Secure・SameSite=Laxのセッションcookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Google IDトークンの検証に失敗した */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description reCAPTCHA検証失敗、またはログイン試行のレート制限超過 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウト成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 拠点一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sites: components["schemas"]["Site"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreateRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: components["parameters"]["SiteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    issueClaimCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimCodeCreateRequest"];
            };
        };
        responses: {
            /** @description 発行成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimCodeCreateResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description reCAPTCHA検証失敗、またはコード発行のレート制限超過 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    claimDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceClaimRequest"];
            };
        };
        responses: {
            /** @description クレーム成立・デバイストークン発行 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceClaimResponse"];
                };
            };
            /** @description コードが不正・期限切れ・使用済み、または失敗回数上限により失効済み */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description IP単位のクレーム試行レート制限超過 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDevices: {
        parameters: {
            query?: {
                /** @description 指定した場合はその拠点配下のデバイスのみ返す */
                siteId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デバイス一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デバイス詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getDeviceTelemetrySeries: {
        parameters: {
            query: {
                range: "24h" | "7d";
                sensorType: components["schemas"]["SensorTypeCode"];
            };
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 時系列データ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        points: components["schemas"]["TelemetrySeriesPoint"][];
                        /** @description グラフ上に閾値ラインを描画するための現在設定値 */
                        thresholds: components["schemas"]["Threshold"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    ingestTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryIngestRequest"];
            };
        };
        responses: {
            /** @description 受信成功（値域逸脱・重複seqの場合も`accepted`で判別可能な200を返す） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryIngestResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description デバイストークンが無効 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description デバイスが論理削除済み（Gone） */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDeviceThresholds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 閾値一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        thresholds: components["schemas"]["Threshold"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDeviceThresholds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        thresholds: components["schemas"]["Threshold"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCommands: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description コマンド履歴 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        commands: components["schemas"]["Command"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCommand: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandCreateRequest"];
            };
        };
        responses: {
            /** @description 発行成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Command"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAutomationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 自動ルール設定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAutomationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                /** @description カンマ区切りで複数指定可（例：open,acknowledged） */
                status?: components["schemas"]["AlertStatus"][];
                deviceId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description アラート一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        alerts: components["schemas"]["Alert"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    acknowledgeAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ack成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 既にclosed状態のアラートはack不可 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDashboardSitesSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 拠点集計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sites: components["schemas"]["Site"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTodaySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description サマリーあり */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummary"];
                };
            };
            /** @description 当日分は未生成 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    generateDailySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 新規生成成功（データ不足の定型文の場合も201・`dataSufficient=false`） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 当該クォータ日は既に生成済み（1日1回・JST03:00リセット相当） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSummaryQuotaExceeded"];
                };
            };
        };
    };
    adminListDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description デバイス一覧（テナント分離の対象外・管理者のみ） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    adminResetAiQuota: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description リセット成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    internalGenerateSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalAiSummaryRequest"];
            };
        };
        responses: {
            /** @description 生成成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalAiSummaryResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description 内部サービスキーが不正 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
